name = "RationalFunctionFields"
uuid = "73480bc8-48a2-41cc-880f-208b490ccf65"
authors = ["Alexander Demin", "Gleb Pogudin"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
