# Contains example for Section 4.2

using StructuralIdentifiability, RationalFunctionFields, ParamPunPam

# 0. Get the defintion of the example  
include(joinpath(dirname(dirname(pathof(StructuralIdentifiability))), "benchmarking", "benchmarks.jl"))
model = benchmarks[:SEIR34]

# 1. Get the original set of generators
funcs = StructuralIdentifiability.initial_identifiable_functions(model[:ode], prob_threshold=0.99, with_states=false)[1]
println("=======\nSection 4.2\n=======\n")
println("1. Original generators:\n", RationalFunctionFields.dennums_to_fractions(funcs), "\n")

# 2. Compute the coefficients of GB up to degree d=2 
#    (or, (d_num,d_den) = (1,1))
rff = RationalFunctionField(funcs)
deg = (1,1)
rff = RationalFunctionFields.groebner_basis_coeffs(rff, up_to_degree=deg)
gb = rff.oms.cached_groebner_bases[(InputOrdering(), deg)]
cfs = map(f -> collect(coefficients(f)), gb)
cfs_are_enough = fields_equal(RationalFunctionField(cfs), RationalFunctionField(funcs), 0.99)
println("2. Coefficients up to degree d=$deg:\n", cfs)
println("2. They generate the original subfield: ", cfs_are_enough)

# 3. Compute the coefficients of GB up to degree d=4
#    (or, (d_num,d_den) = (2,2))
rff = RationalFunctionField(funcs)
deg = (2,2)
rff = RationalFunctionFields.groebner_basis_coeffs(rff, up_to_degree=deg)
gb = rff.oms.cached_groebner_bases[(InputOrdering(), deg)]
cfs = map(f -> collect(coefficients(f)), gb)
cfs_are_enough = fields_equal(RationalFunctionField(cfs), RationalFunctionField(funcs), 0.99)
println("3. Coefficients up to degree d=$deg:\n", cfs)
println("3. They generate the original subfield: ", cfs_are_enough)

degrees = map(f -> map(c -> total_degree.((numerator(c),  denominator(c))), f), cfs)
@info "Coefficients generate the field at degrees:" degrees
@info "Coefficients:" cfs

polys = RationalFunctionFields.polynomial_generators(rff, 2)
@info "Polynomial generators:" polys

combined = vcat(reduce(vcat, cfs), polys)
combined = filter(!RationalFunctionFields.is_rational_func_const, combined)
@info "Combined:" combined

sorted = sort(unique(combined), lt = RationalFunctionFields.rational_function_cmp)
@info "Sorted:" sorted

simplified = RationalFunctionFields.beautiful_generators(RationalFunctionField(combined))
@info "Simplified:" simplified

gb100 = paramgb(rff.mqs, up_to_degree=(100,100), ordering=DegRevLex())
@info "GB up to degree 100:" gb100

@info "Can be generated by polynomial generators:" RationalFunctionFields.fields_equal(rff, RationalFunctionField(polys), 0.99)
