# Contains examples for Section 7.2: "Identifiability and observability for discrete-time systems"

using Nemo
using RationalFunctionFields

# Helper function: prints simplified generators for subfields generated by 
# the trajectory of discrete-time system
function generate_observable(output, substitution, num_steps)
    shifts = [output]
    for i in 2:num_steps
        println("Number of time points: $i")
        push!(shifts, evaluate(shifts[end], substitution))
        println("Generators:")
        for f in simplified_generating_set(RationalFunctionField(shifts))
            println("\t $f")
        end
    end
end

## Example 7.6: "General fractional-linear model"

println("=======\nExample 7.6\n=======\n")
R, (x, mu1, mu2, mu3, mu4) = polynomial_ring(QQ, ["x", "mu1", "mu2", "mu3", "mu4"])

substitution = [(mu1 * x + mu2) // (mu3 * x + mu4), mu1, mu2, mu3, mu4]
generate_observable(x // one(R), substitution, 5)

## Example 7.7: "Logistic growth"

println("=======\nExample 7.7\n=======\n")
R, (x, mu1, mu2, mu3) = polynomial_ring(QQ, ["x", "mu1", "mu2", "mu3"])

substitution = [x * (1 + mu1 * (1 - x // mu2)), mu1, mu2, mu3]
generate_observable(x * mu3 // one(R), substitution, 4)

## Example 7.8: "SIS/SIR epidemiological model"

println("=======\nExample 7.7\n=======\n")
R, (alpha, beta, gamma, eta, S, I) = polynomial_ring(QQ, ["alpha", "beta", "gamma", "eta", "S", "I"])

substitution = [alpha, beta, gamma, eta, S * (1 - beta * I) + alpha * I, I * (1 + beta * S - gamma - alpha)]
generate_observable(eta * I // one(R), substitution, 5)
