using StructuralIdentifiability, RationalFunctionFields, ParamPunPam

include(joinpath(dirname(dirname(pathof(StructuralIdentifiability))), "benchmarking", "benchmarks.jl"))

model = benchmarks[:SEIR34]
funcs = StructuralIdentifiability.initial_identifiable_functions(model[:ode], prob_threshold=0.99, with_states=false)[1]

rff = RationalFunctionField(funcs)

rff = RationalFunctionFields.groebner_basis_coeffs(rff)
gb_full = rff.mqs.cached_groebner_bases[(InputOrdering(), (typemax(Int), typemax(Int)))]
cfs = map(f -> collect(coefficients(f)), gb_full)
degrees = map(f -> map(c -> total_degree.((numerator(c),  denominator(c))), f), cfs)
@info "Coefficients generate the field at degrees:" degrees
@info "Coefficients:" cfs

polys = RationalFunctionFields.polynomial_generators(rff, 2)
@info "Polynomial generators:" polys

combined = vcat(reduce(vcat, cfs), polys)
combined = filter(!RationalFunctionFields.is_rational_func_const, combined)
@info "Combined:" combined

sorted = sort(unique(combined), lt = RationalFunctionFields.rational_function_cmp)
@info "Sorted:" sorted

simplified = RationalFunctionFields.beautiful_generators(RationalFunctionField(combined))
@info "Simplified:" simplified

gb100 = paramgb(rff.mqs, up_to_degree=(100,100), ordering=DegRevLex())
@info "GB up to degree 100:" gb100

@info "Can be generated by polynomial generators:" RationalFunctionFields.fields_equal(rff, RationalFunctionField(polys), 0.99)
